### ISSUE TITLE
Support globe textures larger than gl.MAX_TEXTURE_SIZE

### ISSUE THREAD

**Issue by botandrose** [slnsw/dxlab-meridian#3]
Hi Kaho!

As requested, here is a screenshot of the error message when trying to use a texture larger than `gl.MAX_TEXTURE_SIZE` which is 4096x4096 on my machine. I also needed to bump three.js from v61 to v72 in order to gain support for `THREE.CanvasTexture`, which apparently is required to support these larger textures.

Honestly, I'm a bit out my league here! While I'm quite experienced in web dev (20 years now, yikes!), this is my first time working with both the Canvas and WebGL APIs, so I very much appreciate any insight you might have!

Thanks again for your help.
 
![Screenshot from 2020-07-31 15-24-46](https://user-images.githubusercontent.com/17391/89082176-0d243380-d342-11ea-9c2c-604748947d37.png)

**Comment by luke-slnsw** [comment]
Hi @botandrose 

Kaho is on holidays for a couple of weeks. I work with him in the DX Lab. I'll have a go at spinning up the code locally and see if I can get a larger image size working.

thanks
-Luke

**Comment by botandrose** [comment]
Thank you, @luke-slnsw!

**Comment by luke-slnsw** [comment]
OK checkout this branch @botandrose : https://github.com/slnsw/dxlab-meridian/tree/hires2020

I created a 20,000px wide map image and a 20,000px wide bump map.
And I updated index.html to pull in a much newer version of THREEjs.

Seems to work.

A few things to note:

- the 20,000px wide bump map was >100MB so won't fit in Github. I made a 8k wide pure B&W version and that is working fine with the 20,000px map image.
- THREEjs complains that the map is >16384px and resizes it to that big, stating this in the console:
"THREE.WebGLRenderer: Texture has been resized from (18000x9000) to (16384x8192)."
- I also fixed the loadTexture issue introduced by the newer version of THREEjs (see changes in app.js)
- Viewing the site really slows my machine down, might be unwise to use images quite this large.

Hope that helps...
:L

**Comment by botandrose** [comment]
@luke-slnsw Thank you for taking a stab at this! I spun up your branch and I have discovered that the texture limit I was hitting (4096px^2), and the one you were hitting (16384px^2), are actually the same limit: `gl.MAX_TEXTURE_SIZE`! This limit apparently varies from machine to machine. So, when I loaded the page, the texture is still the same low-resolution as it is on the master branch, with the following in the error console: "THREE.WebGLRenderer: Texture has been resized from (18000x9000) to (4096x2048)." I'm going to rename this issue accordingly.

I _think_ the path beyond this limit is to switch to rendering the map image on a canvas element, and then mapping it to the globe with `THREE.CanvasTexture`. I tried this, but my attempts resulted in the cryptic errors seen above in the screenshot. Do they make any sense to you? I'm not familiar with the Canvas and WebGL APIs!  

Lastly, as an aside, I see that you have changed the whitespace from tabs to spaces. Thank god! My editor really struggles with tabs! However, all of the changes you've made are in one commit, so when I run a diff to try to see exactly what you've changed, it shows every line! Would you mind committing the whitespace fix separately from the other changes?

**Comment by luke-slnsw** [comment]
Hi again 

sorry for the delay - other projects and some leave are to blame.

OK if you pull in the latest from that branch you'll see I've got the globe working using a canvas as the texture. 

See app.js lines 236-257 and 266.

There are several sizes of map to choose from in lines 22-26. The canvas size is set to the size of the image before being applied as the texture. Not sure why but anything bigger than 16384 fails silently for some reason.

Let me know what you think @botandrose 

cheers
:L

**Comment by botandrose** [comment]
Oh wow! This is really exciting. Thank you for much for putting more time and energy into this. I'm going to pull it down at take a look and verify that it fixes the issue on my more modest machine, as well, but it looks very very promising!

**Comment by botandrose** [comment]
@luke-slnsw Confirmed hi-res globe on my crappy mobile GPU!!! Wow, this is so wonderful, Luke. Thank you, thank you, thank you! This gives us everything we need to push forward with David's plans. I really appreciate your time and effort here!
